name: deals_dray
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.2
  intl_phone_number_input: ^0.7.4
  animate_do: ^3.3.4
  flutter_otp_text_field: ^1.1.3+2
  http: ^1.2.2
  device_info: ^2.0.3
  intl_phone_field: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Lottie/
